### PR TITLE
feat: use auto update pwa register type

### PR DESCRIPTION
**Pull request by userquin**
This PR also includes:
- update deps to latest: vite (4.5.0), vue and vite vue plugin
- include package manager and type module in package.json file (updated to latest available version 8.10.3)
- use dynamic async component for tools page: changed in `src/router/index.ts` module
- use dynamic import to load assets-generator module  in the tools page: load it only when required, that's, when the user clicks the generate button (the promise will resolve only once)
- include svgo to `optimizeDeps.needsInterop` to speed up cold start
- fixed some VueUse `useXXX` composables, using undefined instead null

Before these changes, the build output was:

image

Building with these changes (home and tools pages should load faster):

image

### CODE REVIEW

**Comment by userquin** [comment]
We should also include webp and wasm file extensions in workbox glob patterns.

**Comment by userquin** [comment]
You should remove console.log, there are a few in ts modules

**Comment by userquin** [comment]
You can try to use [UnoCSS Preset Icons](https://unocss.dev/presets/icons) and replace all svg libraries used here (if you can use css classes), Iconify has ~150 icon sets and 200K+ available icons: check available collections and icons in [Icônes](https://icones.js.org/) or [Iconify Icon Sets](https://icon-sets.iconify.design/)

**Comment by rwv** [comment]
thanks!

**Pull request merged**
